LikeLionHGU/makeup

src/App.js, src/account/SignUp.js, src/header/Header.module.css, src/header/login/Login.js
=> feat : 회원가입 기능 구현

src/header/Header.js
=> chore : 경로 변경

src/App.js, src/account/LogIn.js, src/account/SignUp.js
=> [feat] : 로그인 기능 구현

src/calendar/Calendar.jsx, src/calendar/calendar.module.css
=> feat - 시간 예약 기능 구현

src/modal/Modal.module.css, src/write/BoardWrite.js, src/write/BoardWrite.module.css
=> style : 게시글 여러 스타일 수정

src/write/BoardWrite.module.css
=> style : 게시글 css 수정

src/App.js, src/calendar/Calendar.css, src/calendar/Calendarr.jsx, src/calendar/Calendarr.module.css
=> style : 캘린더 데이트피커

src/App.js, src/calendarMento/MentoCalendar.jsx, src/grid/Grid.jsx
=> style : 멘티 멘토 달력 구분

src/calendar/Calendar.css, src/calendar/Calendarr.module.css
=> style : 캘린더 css

src/banner/Banner.module.css, src/banner/Slider.jsx, src/banner/Slider.module.css, src/calendar/Calendar.css, src/calendar/Calendarr.module.css, src/grid/Grid.jsx, src/modal/modal.js
=> style : 여러가지

src/account/Complete.jsx, src/account/LogIn.js, src/account/LogIn.module.css, src/account/SignUp.js, src/account/SignUp.module.css
=> feat : 로그인 / 회원가입 api 연결

src/calendarMento/MentoCalendar.jsx
=> feat : 캘린더 멘토 api 연결

src/calendar/Calendar.css, src/uploadPost/UploadPost.module.css, src/write/BoardWrite.js, src/write/BoardWrite.module.css
=> style : absolute 수정 및 css 수정

src/account/LogIn.js, src/account/SignUp.js, src/calendarMento/MentoCalendar.jsx
=> feat : 로그인 api 연결

src/App.js, src/grid/Grid.jsx, src/uploadPost/UploadPost.jsx
=> feat : 최근 게시물 피드 수정

src/calendarMento/MentoCalendar.jsx, src/header/search/Search.js, src/search/SearchBoard.jsx
=> feat : 캘린더 기능 구현 및 api 연결

src/App.js, src/calendar/Calendarr.jsx, src/calendarMento/MentoCalendar.jsx, src/uploadPost/UploadPost.jsx, src/uploadPost/UploadPost.module.css, src/write/BoardWrite.js
=> Hayoung feat/#97

src/header/search/Search.js, src/search/SearchBoard.jsx
=> feat : 검색 기능 갈작대기

src/calendar/Calendarr.jsx, src/grid/Grid.jsx, src/modal/modal.js
=> feat : 다양한 기능

src/header/Header.module.css, src/uploadPost/UploadPost.module.css
=> style : 글씨체 및 마진값 변경
